rust-lang/rust-semverver

Cargo.toml, README.md
It appears that the repository was moved from the nursery to dev-tools, but the paths were not updated.
=> Update paths from rust-lang-nursery to rust-dev-tools

Cargo.toml, src/bin/cargo_semver.rs, src/semcheck/mapping.rs, src/semcheck/mismatch.rs, src/semcheck/translate.rs, src/semcheck/traverse.rs
This updates cargo to 0.34 (master) - cargo removed some APIs that rust-semverver was using ~~apparently accidentally, so I've filled in a PR to revert their removal: https://github.com/rust-lang/cargo/pull/6517 . This PR currently points to my branch of cargo with that patch, and I'll update this PR to cargo 0.34 once it is properly released.~~ 
~~Until then, it would be nice to check that this PR doesn't break anything on CI.~~ 
EDIT: these APIs won't be re-added to cargo any time soon, and there are currently no alternatives available. We should probably stop depending on `cargo` in the future as suggested in that PR, but that might need some major changes (I've filled an issue in the `cargo_metadata` repo about how to proceed here: https://github.com/oli-obk/cargo_metadata/issues/60). …
=> Update cargo to 0.34

Cargo.toml, src/bin/cargo_semver.rs, src/bin/rust_semverver.rs, src/semcheck/mapping.rs, src/semcheck/mismatch.rs, src/semcheck/translate.rs, src/semcheck/traverse.rs
Instead of having a custom `CompilerCalls` impl, the analysis pass
is just injected into the default compiler. 
r? @oli-obk  - I hope I updated this properly like we talked about on discord, but I would prefer if you would take a look at this. All the tests pass on my machine, but this still does not fix #81 (I'll send a PR for that afterwards).
=> Update rust-semverver driver 

src/bin/cargo_semver.rs, src/lib.rs, src/mapping.rs
Compilation is broken on nightly
=> Fix compilation

ci/run.sh, src/bin/cargo_semver.rs, src/bin/rust_semverver.rs, src/changes.rs, tests/cases/regions/stdout, tests/examples.rs, tests/full.rs, tests/full_cases/libc-0.2.28-0.2.31.linux, tests/full_cases/libc-0.2.28-0.2.31.osx, tests/full_cases/libc-0.2.47-0.2.48.osx
So it turned out that the bug with rust-semverver returning an incorrect exit code on error (it always returned success) wasn't in rust-semverver, but in rustc itself. This is now fixed upstream (https://github.com/rust-lang/rust/pull/58400), which makes all tests that should return an error exit code fail. This PR fixes that.
=> Fix exit code of rust-semverver in tests

src/bin/cargo_semver.rs, tests/full.rs
The current setup in `tests/full.rs` uses awk to filter cargo-semver's output and has a bunch of platform-specific code in order to handle this.
This PR changes the tests to instead filter the output using pure rust.
It also introduces a `-q` flag to cargo-semver that tells it to only output its own messages and not ones from cargo itself. This makes the filtering considerably simpler.
=> Less awkward tests

build.rs, tests/full.rs
Currently, `tests/full.rs` will overwrite the files containing the expected output of cargo-semver with its actual output, then call `git diff` to see if there are any changes. This has a couple of downsides as discussed in #99.
This PR changes the behavior to do the following instead:
1. Capture the new output in memory and compare it against the stored version.
2. If they differ, put the new version into $OUT_DIR for inspection.
3. To make up for the lost functionality from `git diff`, suggest a command to view the diff.
This means that tests can now run even if the source directory is read-only, not checked out via git, or if git is not installed at all. It also means that failing tests do not cause a dirty working tree any more and `cargo clean` as well as `git clean -x` work as …
=> Make `tests/full.rs` no longer use `git diff`

README.md, ci/run.sh, rust-toolchain, src/mapping.rs
`AssocKind` doesn't implement `Eq` and `Hash` anymore.
=> Rustup to rustc 1.40.0-nightly (87cbf0a54 2019-11-01)

.travis.yml, ci/run.sh, src/bin/cargo_semver.rs, src/mapping.rs, src/mismatch.rs, src/traverse.rs, tests/cases/addition/stdout, tests/cases/addition_path/stdout, tests/cases/addition_use/stdout, tests/cases/bounds/stdout, tests/cases/consts/stdout, tests/cases/func/stdout, tests/cases/inherent_impls/stdout, tests/cases/macros/stdout, tests/cases/mix/stdout, tests/cases/pathologic_paths/stdout, tests/cases/sealed_traits/stdout, tests/cases/structs/stdout, tests/cases/trait_impls/stdout, tests/cases/traits/stdout, tests/full_cases/libc-0.2.28-0.2.31.linux, tests/full_cases/libc-0.2.28-0.2.31.osx, tests/full_cases/log-0.3.4-0.3.8.linux, tests/full_cases/log-0.3.4-0.3.8.osx, tests/full_cases/log-0.3.4-0.3.8.windows_msvc, tests/full_cases/rmpv-0.4.0-0.4.1.linux, tests/full_cases/rmpv-0.4.0-0.4.1.osx, tests/full_cases/rmpv-0.4.0-0.4.1.windows_msvc
Caused by rust-lang/rust#70164.
r? @ibabushkin
=> Rustup to the latest nightly

ci/run.sh, rust-toolchain
Lightweight version of #131 - it'd be good to start with a good working base and incrementally work from there.
r? @Manishearth
=> Pin nightly version to a latest one known to be working

.github/workflows/ci.yml
See https://forge.rust-lang.org/infra/docs/bors.html#adding-a-new-repository-to-bors
=> Add a final GHA check for bors

src/bin/cargo_semver.rs
Otherwise it errors out with a "lost build artifact", which may be hard to decipher.
Discovered this when running `cargo semver` on a package that is only a binary - while it seems obvious (there's no public crate API in the first place), the original error message left me wondering if there is something wrong with the build artifact (e.g. internal logic error or multiple `cargo` instances running for the same target). Hopefully, this will make it more clear that it only works on a package with `[lib]` target.
cc @ibabushkin 
r? @Manishearth
=> Properly warn if a package lacks [lib] target

.github/workflows/ci.yml
Otherwise the bot is not informed whether its merge successfully passed the CI test suite.
=> Trigger CI for bors-managed `auto` branch

Cargo.toml, src/bin/cargo-semver.rs
The main change is in https://github.com/rust-lang/rust-semverver/commit/89384957cc45432e63bb026dde2c2a17c341df58, which works around https://github.com/rust-lang/cargo/pull/8236 that introduced different mechanism to output stdio/shell-based data. 
Everything now goes through cargo `Shell` type so `std::io::set_print` trick stopped working - instead, we create our custom shell and fetch the build plan through it.
r? @Manishearth or @ibabushkin
=> Bump Cargo to 0.48

src/bin/cargo-semver.rs
Fixes #125 
```
Benchmark #1: cargo semver -S libc:0.2.28 -C libc:0.2.31
Time (mean ± σ):     810.7 ms ±  16.1 ms    [User: 639.3 ms, System: 97.9 ms]
Range (min … max):   787.2 ms … 841.7 ms    10 runs
Benchmark #2: cargo semver -S log:0.3.4 -C log:0.4.0
Time (mean ± σ):     897.0 ms ±  13.4 ms    [User: 901.3 ms, System: 160.0 ms]
Range (min … max):   869.6 ms … 913.9 ms    10 runs
Benchmark #3: cargo semver -S rmpv:0.4.0 -C rmpv:0.4.1
Time (mean ± σ):      3.373 s ±  0.032 s    [User: 4.984 s, System: 0.651 s]
Range (min … max):    3.308 s …  3.414 s    10 runs
Benchmark #4: cargo semver -S serde_json:1.0.0 -C serde_json:1.0.40
Time (mean ± σ):      9.437 s ±  0.066 s    [User: 12.480 s, System: 0.649 s]
Range (min … max):    9.329 s …  9.519 s    10 runs
```
```
Benchmark #1: cargo …
```
=> Speed compilation by using .rmeta over .rlib files

ci/setup-toolchain.sh
The scheduled CI fails because we don't have `nightly` toolchain, but `nightly-20XX-XX-XX` on CI (https://github.com/rust-lang/rust-semverver/actions/runs/380029548). Since we specify the toolchain via `rust-toolchain`, I think `+nightly` isn't needed here.
=> Do not specify `nightly` in favor of `rust-toolchain`

ci/setup-toolchain.sh
Closes #147 
Otherwise the `rustup override` is effective only in the `ci/` directory, which is not what we want.
Tested locally and seems to be working as intended.
r? @JohnTitor
=> Don't set override in CI script's dir

ci/run.sh, rust-toolchain
So that we don't have to run `rustup component add ...` anymore.
=> Use new format `rust-toolchain`

Cargo.lock
Mainly to prune our dependency tree and to fix some unsafety wrt SocketAddr (https://github.com/rust-lang/rust/pull/78802).
=> Update some deps

Cargo.toml, README.md, rust-toolchain
Follow-up to #173.
- Replace `rust-dev-tools` with `rust-lang`
- Add some comments to sync with nightly date between rust-toolchain and README
=> Clean-up docs

Cargo.lock, Cargo.toml
log:
```
Updating cargo v0.51.0 -> v0.52.0
Updating crates-io v0.31.1 -> v0.33.0
```
Closes #180
=> Update `cargo` and `crates-io` deps

README.md
crates.io's version is outdated and we haven't figured out the release process yet.
cc #168
Closes #184
=> Update the instruction not to install via crates.io

tests/examples.rs
Shelling out to `rm` will not work on Windows.
=> Use remove_file instead of shelling out to `rm`

README.md, rust-toolchain, src/changes.rs, src/mapping.rs, src/mismatch.rs, src/translate.rs, src/traverse.rs, src/typeck.rs, tests/cases/func/new.rs, tests/cases/func/old.rs, tests/cases/func/stdout, tests/cases/inherent_impls/stdout, tests/cases/pathologic_paths/stdout, tests/cases/traits/stdout, tests/examples.rs, tests/full.rs, tests/full_cases/log-0.3.4-0.3.8.linux, tests/full_cases/log-0.3.4-0.3.8.osx, tests/full_cases/log-0.3.4-0.3.8.windows_msvc, tests/full_cases/rmpv-0.4.0-0.4.1.linux, tests/full_cases/rmpv-0.4.0-0.4.1.osx, tests/full_cases/rmpv-0.4.0-0.4.1.windows_msvc
This needed mostly changes around `Predicate` and `Binder`.
Also re-blessed snapshots, some of which improved by pointing only to
the item signature instead of its whole body.
This is the first time I am touching rustc internals, so I am not 100% confident with that change, however all the tests pass, and some of the snapshots are even improving.
=> Update to nightly-2021-05-21

README.md, rust-toolchain, src/bin/cargo-semver.rs, src/bin/rust-semver-public.rs, src/bin/rust-semverver.rs, src/changes.rs
=> Rustup to nightly-2021-07-23

Cargo.lock, Cargo.toml
This PR:
- updates some deps via `cargo update`
- disables default features of `quickcheck` to remove an old `env_logger` that we don't use currently.
=> Some dependency updates

src/changes.rs, tests/cases/structs/new.rs, tests/cases/structs/old.rs, tests/cases/structs/stdout
This comes from https://github.com/rust-lang/libc/pull/2451.
Before this PR, the `kinfo_proc` struct only had one field which was private. I added the missing fields and made them all public. It doesn't seem to be a semver breaking change as the code using this struct previously will still work exactly the same.
=> More flexible rule around adding public fields to struct with private fields

.github/dependabot.yml
Rebasing needs re-approvals for dependabot PRs when we use bors, it's annoying. This disables that behavior and we can explicitly do it via the command, `@bot rebase` if needed.
=> Do not rebase dependabot PRs automatically

Cargo.lock, Cargo.toml
Fixes #246 by pinning proc_macro2 to the last version compatible with recommended nightly-2021-09-30.
=> Pin proc_macro2 dependency to v1.0.32

Cargo.toml
This pins the version of quote to `1.0.10`, which fixes the installation issue in https://github.com/rust-lang/rust-semverver/issues/257
=> fix: pin quote to 1.0.10

README.md, rust-toolchain, src/translate.rs, src/traverse.rs, src/typeck.rs, tests/cases/pathologic_paths/stdout
Attempting to update the nightly toolchain version. I don't know what I'm getting into, but I'll try my best 😅
I understand there were CI issues with nightly-2021-10-15 in #227, but the logs are gone from that time. I will push each nightly upgrade as its own commit in this PR so we can see CI for each.
=> Update nightly toolchain

src/lib.rs, src/traverse.rs
The corresponding feature has been stabilized in rust-lang/rust#79278,
merged 2021-03-22.
=> Apply or-patterns clippy suggestion

src/mapping.rs
No longer necessary, since `rustc_middle::ty::AssocKind` implements
`Hash` and `Eq` again.
=> Revert manually implementing `Hash` for `InherentEntry`

README.md, rust-toolchain, src/mapping.rs, src/mismatch.rs, src/traverse.rs
Seems i missed those in the last big upgrade PR. This should make the nightly CI job using `rustc`'s nightly `master` build green again.
=> Update rustc to nightly-2022-04-20

src/traverse.rs, tests/full.rs, tests/full_cases/config-0.13.0-0.13.1.linux, tests/full_cases/config-0.13.0-0.13.1.osx, tests/full_cases/config-0.13.0-0.13.1.windows_msvc
The `#[async_trait]` attribute/crate does a transformation to all async
methods, which as far as i can tell removes the `&self` lifetime, so our
logic to offset by 1 if `has_self == true` for both compared types has
an off-by-one-error here. This didn't error out earlier, since
`get_region_from_params` uses `Vec::get`, so "this index is out of
bounds" is just as `None` as "this generic param is not of kind
lifetime".
Also this is more a workaround than a fix. I'm not sure if we can do
something cleverer than "check if the last lifetim's name is
`'async_trait`".
=> Work around async_trait behavior

.github/workflows/style.yml
The overall label "Shellcheck" somewhat hid the `clippy` and `rustfmt` runs underneath, so change it to "Style and Linters"
=> Update style check CI job descriptions

Cargo.lock, Cargo.toml, src/bin/cargo-semver.rs
Address the changes on https://github.com/rust-lang/cargo/pull/10064
=> Upgrade Cargo to 0.62.0

README.md
Closes https://github.com/rust-lang/rust-semverver/issues/306
Also we should encourage use of the nightly install for CI to achieve better stability.
=> Update README installation instructions to use nightly-2022-05-16 (#306)

.github/workflows/ci.yml
Implements #299 
fixes https://github.com/rust-lang/rust-semverver/issues/299
=> Create an issue on nightly CI run failure

.github/workflows/style.yml, scripts/toolchain-version
=> Add script to update and check nightly version consistency

.github/workflows/publish.yml
Triggered by tag push or manually from the actions interface.
fixes #300
=> Add publish job for crates.io

README.md, rust-toolchain, tests/full_cases/config-0.13.0-0.13.1.linux, tests/full_cases/config-0.13.0-0.13.1.osx, tests/full_cases/config-0.13.0-0.13.1.windows_msvc
Fixes #332
Signed-off-by: Yuki Okushi <jtitor@2k36.org>
=> Rustup to rust-lang/rust#98320
